// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: modules/auth/authProtobuf/auth.proto

package go_oauth_server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessTokenCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessTokenCheckRequest) Reset() {
	*x = AccessTokenCheckRequest{}
	mi := &file_modules_auth_authProtobuf_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessTokenCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessTokenCheckRequest) ProtoMessage() {}

func (x *AccessTokenCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modules_auth_authProtobuf_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessTokenCheckRequest.ProtoReflect.Descriptor instead.
func (*AccessTokenCheckRequest) Descriptor() ([]byte, []int) {
	return file_modules_auth_authProtobuf_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AccessTokenCheckRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type AccessTokenCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=isValid,proto3" json:"isValid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessTokenCheckResponse) Reset() {
	*x = AccessTokenCheckResponse{}
	mi := &file_modules_auth_authProtobuf_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessTokenCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessTokenCheckResponse) ProtoMessage() {}

func (x *AccessTokenCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modules_auth_authProtobuf_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessTokenCheckResponse.ProtoReflect.Descriptor instead.
func (*AccessTokenCheckResponse) Descriptor() ([]byte, []int) {
	return file_modules_auth_authProtobuf_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AccessTokenCheckResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

type RoleCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleCountRequest) Reset() {
	*x = RoleCountRequest{}
	mi := &file_modules_auth_authProtobuf_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleCountRequest) ProtoMessage() {}

func (x *RoleCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modules_auth_authProtobuf_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleCountRequest.ProtoReflect.Descriptor instead.
func (*RoleCountRequest) Descriptor() ([]byte, []int) {
	return file_modules_auth_authProtobuf_auth_proto_rawDescGZIP(), []int{2}
}

type RoleCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleCountResponse) Reset() {
	*x = RoleCountResponse{}
	mi := &file_modules_auth_authProtobuf_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleCountResponse) ProtoMessage() {}

func (x *RoleCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modules_auth_authProtobuf_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleCountResponse.ProtoReflect.Descriptor instead.
func (*RoleCountResponse) Descriptor() ([]byte, []int) {
	return file_modules_auth_authProtobuf_auth_proto_rawDescGZIP(), []int{3}
}

func (x *RoleCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_modules_auth_authProtobuf_auth_proto protoreflect.FileDescriptor

const file_modules_auth_authProtobuf_auth_proto_rawDesc = "" +
	"\n" +
	"$modules/auth/authProtobuf/auth.proto\";\n" +
	"\x17AccessTokenCheckRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\"4\n" +
	"\x18AccessTokenCheckResponse\x12\x18\n" +
	"\aisValid\x18\x01 \x01(\bR\aisValid\"\x12\n" +
	"\x10RoleCountRequest\")\n" +
	"\x11RoleCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count2\x8e\x01\n" +
	"\x0fAuthGrpcService\x12G\n" +
	"\x10AccessTokenCheck\x12\x18.AccessTokenCheckRequest\x1a\x19.AccessTokenCheckResponse\x122\n" +
	"\tRoleCount\x12\x11.RoleCountRequest\x1a\x12.RoleCountResponseB'Z%github.com/Pratchaya0/go-oauth-serverb\x06proto3"

var (
	file_modules_auth_authProtobuf_auth_proto_rawDescOnce sync.Once
	file_modules_auth_authProtobuf_auth_proto_rawDescData []byte
)

func file_modules_auth_authProtobuf_auth_proto_rawDescGZIP() []byte {
	file_modules_auth_authProtobuf_auth_proto_rawDescOnce.Do(func() {
		file_modules_auth_authProtobuf_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_auth_authProtobuf_auth_proto_rawDesc), len(file_modules_auth_authProtobuf_auth_proto_rawDesc)))
	})
	return file_modules_auth_authProtobuf_auth_proto_rawDescData
}

var file_modules_auth_authProtobuf_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_modules_auth_authProtobuf_auth_proto_goTypes = []any{
	(*AccessTokenCheckRequest)(nil),  // 0: AccessTokenCheckRequest
	(*AccessTokenCheckResponse)(nil), // 1: AccessTokenCheckResponse
	(*RoleCountRequest)(nil),         // 2: RoleCountRequest
	(*RoleCountResponse)(nil),        // 3: RoleCountResponse
}
var file_modules_auth_authProtobuf_auth_proto_depIdxs = []int32{
	0, // 0: AuthGrpcService.AccessTokenCheck:input_type -> AccessTokenCheckRequest
	2, // 1: AuthGrpcService.RoleCount:input_type -> RoleCountRequest
	1, // 2: AuthGrpcService.AccessTokenCheck:output_type -> AccessTokenCheckResponse
	3, // 3: AuthGrpcService.RoleCount:output_type -> RoleCountResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_modules_auth_authProtobuf_auth_proto_init() }
func file_modules_auth_authProtobuf_auth_proto_init() {
	if File_modules_auth_authProtobuf_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_auth_authProtobuf_auth_proto_rawDesc), len(file_modules_auth_authProtobuf_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_auth_authProtobuf_auth_proto_goTypes,
		DependencyIndexes: file_modules_auth_authProtobuf_auth_proto_depIdxs,
		MessageInfos:      file_modules_auth_authProtobuf_auth_proto_msgTypes,
	}.Build()
	File_modules_auth_authProtobuf_auth_proto = out.File
	file_modules_auth_authProtobuf_auth_proto_goTypes = nil
	file_modules_auth_authProtobuf_auth_proto_depIdxs = nil
}
